Merge upstream LibreELEC 12.2 into Lakka v6.1 (#2109)
* rtw88: add led locking patch to resolve dropped connections

* addons: sync code cleanup from LE13

* rtmpdump: update to a non-geoblocked source URL

Signed-off-by: Christian Hewitt <christianshewitt@gmail.com>

* dvblast: update to a non-geoblocked source URL

Signed-off-by: Christian Hewitt <christianshewitt@gmail.com>

* rust: update to 1.82.0

- fix aarch64 build with llvm
- fix config warning

before:

Building bootstrap
running: /build/rust-1.82.0/rust-snapshot/bin/cargo build --manifest-path /build/rust-1.82.0/src/bootstrap/Cargo.toml --verbose --frozen
warning: `/build/rust-1.82.0/cargo_home/config` is deprecated in favor of `config.toml`
note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`

after:

Building bootstrap
running: /build/rust-1.82.0/rust-snapshot/bin/cargo build --manifest-path /build/rust-1.82.0/src/bootstrap/Cargo.toml --verbose --frozen

* cargo-snapshot: update to 1.82.0

* rust-std-snapshot: update to 1.82.0

* rustc-snapshot: update to 1.82.0

* evtest: update to a non-geoblocked source URL

Signed-off-by: Christian Hewitt <christianshewitt@gmail.com>

* linux (RPi): update to 6.12.41-ac69f09

Signed-off-by: Matthias Reichl <hias@horus.com>

* rpi-eeprom: update to 6f692d1

Signed-off-by: Matthias Reichl <hias@horus.com>

* linux (RPi): update to 6.12.41-4c4a5be

Signed-off-by: Matthias Reichl <hias@horus.com>

* linux (RPi): update to 6.12.42-2fa00bc

Signed-off-by: Matthias Reichl <hias@horus.com>

* linux (RPi): config options for 6.12.42-2fa00bc

Signed-off-by: Matthias Reichl <hias@horus.com>

* iwlwifi-firmware: update to githash 042ba27

- supports Linux 6.16

* mesa: add patch with backport of mesa MR 36870

This fixes a huge memory leak when using EGL rendering

Signed-off-by: Matthias Reichl <hias@horus.com>

* rtmpdump: drop upstreamed patch

* cargo-snapshot: update to 1.85.1

* rust-std-snapshot: update to 1.85.1

* rustc-snapshot: update to 1.85.1

* rust: update to 1.85.1

set the config.toml to not download ci llvm for bootstrap build

* Revert "bottom: update to 0.11.1"

This reverts commit c99f8c91eaca41176897aa3c918038e2ae3636e5.

due to bottom requiring >= rust-1.88, rust is not upgradeable past 1.85.1 without llvm-19+

    error: rustc 1.85.1 is not supported by the following package:
      sysinfo@0.37.0 requires rustc 1.88

* docker/jammy: fix caching of apt update

* docker/noble: fix caching of apt update

* addons: automated code cleanup

Signed-off-by: Ian Leonard <antonlacon@gmail.com>

* pvr.waipu: update 21.12.3-Omega to 21.12.5-Omega

* imagedecoder.heif: update 21.0.2-Omega to 21.0.3-Omega

* librespot: update to 0.7.0 and addon (1)

* minisatip: update to 2.0.26 and addon (1)

* syncthing: update to 2.0.3 and addon (3)

* samba: update to 4.22.4

Release notes:
- https://www.samba.org/samba/history/samba-4.22.4.html

* mesa: update to 25.1.9

* spirv-llvm-translator: update to 19.1.10

* llvm: update to 19.1.7

* minisatip: update to 2.0.27 and addon (2)

* librespot: update to 0.7.1 and addon (2)

* pvr.hdhomerun: update 21.0.2-Omega to 21.0.3-Omega

* linux: update and fix RK3288/RK3328/RK3399 patches

Signed-off-by: Christian Hewitt <christianshewitt@gmail.com>

* go: update to 1.25.1

* rsyslog: update to 8.2508.0 and addon (1)

* syncthing: update to 2.0.6 and addon (4)

* iw: update to 6.17

* pvr.hdhomerun: update 21.0.3-Omega to 21.0.4-Omega

* linux (Samsung): update .config for 6.16.1

* linux (Rockchip RK3399): update .config for 6.16.1

* linux (Rockchip RK3328): update .config for 6.16.1

* linux (Rockchip RK3288): update .config for 6.16.1

* linux (Qualcomm): update .config for 6.16.1

* linux (NXP iMX8): update .config for 6.16.1

* linux (NXP iMX6): update .config for 6.16.1

* linux: update to 6.16.4

* netavark: update to 1.16.1

* podman-bin: update to 5.6.1

* moby: update to 28.4.0

* cli: update to 28.4.0

* runc: update to 1.3.1

* podman: update to 5.6.1 and addon (1)

- runc: update to 1.3.1
- podman-bin: update to 5.6.1
- netavark: update to 1.16.1

* docker: update to 28.4.0 and addon (1)

- runc: update to 1.3.1
- cli: update to 28.4.0
- moby: update to 28.4.0

* minisatip: update to 2.0.28 and addon (3)

* syncthing: update to 2.0.7 and addon (5)

* dool: update to 1.3.8

* evtest: update to 1.36

* stress-ng: update to 0.19.04

* system-tools: update addon (4)

- stress-ng: update to 0.19.04
- evtest: update to 1.36
- dool: update to 1.3.8

* jdk-arm-zulu: update to 8.88.0.19-8.0.462

* jdk-aarch64-zulu: update to 8.88.0.19-8.0.462

* jdk-x86_64-zulu: update to 8.88.0.19-8.0.462

* jre.zulu: update to 8.88.0.19-8.0.462 and addon (1)

* rust: update to 1.89.0

- sync change-id
- fix aarch64 build against llvm
  - https://github.com/llvm/llvm-project/commit/c9f27275c1330a325661bdf14fb3bc444a5e3648

* rust-std-snapshot: update to 1.89.0

* rustc-snapshot: update to 1.89.0

* cargo-snapshot: update to 1.89.0

* llvm: add llc and llvm-... as required by rust-1.89.0

- include llvm- and obj on all target llvm builds to support rust
- fixes aarch64 and arm rust target builds

* bottom: update to 0.11.1

* system-tools: update addon (5)

- bottom: update to 0.11.1

* oscam: update to 11886, include missing shared library and addon (1)

* pcscd: do not use polkit and addon (1)

* oscam: fix RPATH on libpcsclite and addon (2)

* syncthing: update to 2.0.8 and addon (6)

* dotnet-runtime: update to 8.0.20 and addon (1)

* aspnet8-runtime: update to 8.0.20

* docker-compose: update to 2.39.3

* btrfs-progs: update to 6.16.1 and addon (2)

* minisatip: update to 2.0.30 and addon (4)

* libxss: update to 1.2.5 and meson

* libXScrnSaver: update to 1.2.5 and meson

* gtk3: update to 3.24.50

* at-spi2-core: update to 2.57.2

* cups: update to 2.4.14

* chrome: update to 140.0.7339.127 and addon (1)

- cups: update to 2.4.14
- at-spi2-core: update to 2.57.2
- gtk3: update to 3.24.50
- libXScrnSaver: update to 1.2.5 and meson
- libxss: update to 1.2.5 and meson

* linux: update to 6.16.7

* RPi: update to firmware 511dd35

Signed-off-by: Matthias Reichl <hias@horus.com>

* rpi-eeprom: update to 1793f5c

Signed-off-by: Matthias Reichl <hias@horus.com>

* linux (RPi): update to 6.12.44-6c61955

Signed-off-by: Matthias Reichl <hias@horus.com>

* linux (RPi): config options for 6.12.44-6c61955

Signed-off-by: Matthias Reichl <hias@horus.com>

* rpi-eeprom: update to f45ed23

Signed-off-by: Matthias Reichl <hias@horus.com>

* linux (RPi5): enable realtek 8169 driver

Signed-off-by: Matthias Reichl <hias@horus.com>

* linux (RPi): update to 6.12.45-1d80b65

Signed-off-by: Matthias Reichl <hias@horus.com>

* linux (RPi): update to 6.12.47-359f37f

Signed-off-by: Matthias Reichl <hias@horus.com>

* kodi: bump to 9efd536

Signed-off-by: Christian Hewitt <christianshewitt@gmail.com>

* openssl: update to 3.5.3

Release notes:
- https://www.openssl.org

Release notes:
- https://www.openssl.org/news/vulnerabilities.html

* x264: update to githash b35605a (3222)

* ffmpegx: avcodec/hw_base_encode: fix NULL dereference if no frames before end-of-stream

- https://patchwork.ffmpeg.org/series/15013/mbox/
- https://patchwork.ffmpeg.org/project/ffmpeg/patch/20250719070836.283597-1-jahutchinson99@googlemail.com/
- https://github.com/tvheadend/tvheadend/issues/1833

* tvheadend43: update to githash 7cbe50c and addon (1)

Log:
- https://github.com/tvheadend/tvheadend/compare/f1c460feba34491d473c60216bd35eccc73c178e...7cbe50c6e646e0d2443ef5bd73ba3c49c3c632c3

* ffmpeg-tools: update addon (1)

* nextpvr: update addon (1)

* pvr.teleboy: update 21.0.0-Omega to 21.0.1-Omega

* librelp: update to 1.12.0

* rsyslog: update addon (2)

- librelp: update to 1.12.0

* filebrowser: update to 2.43.0 and addon (2)

* syncthing: update to 2.0.9 and addon (7)

* asio: update to 1.36.0

* snapcast: update to 0.33.0

* snapclient: update to 0.33.0 and addon (1)

* snapserver: update to 0.33.0 and addon (1)

* minisatip: update to 2.0.34 and addon (5)

* iwd: update to 3.10

log:
- https://git.kernel.org/pub/scm/network/wireless/iwd.git/log/

* iwlwifi-firmware: update to githash 8f70df6

* linux: update to 6.16.9

* inputstream.adaptive: update to 21.5.16-Omega

Signed-off-by: Matthias Reichl <hias@horus.com>

* alsa-tools: fix 90-alsa-restore.rules

Drop the meaningless NAME setting and add SUBSYSTEM=="sound", like in
the upstream rule.

Signed-off-by: Matthias Reichl <hias@horus.com>

* rpi-cirrus-config: fix 90-alsa-restore.rules

Drop the meaningless NAME= and reorder tests that ACTION is
the first one.

Signed-off-by: Matthias Reichl <hias@horus.com>

* bluez: fix bluetooth.service unit

Align our bluetooth.service unit with upstream:

Specify the correct dbus service type, add bus name and add
the alias so pulseaudio stops complaining about the missing
dbus-org.bluez.service

Signed-off-by: Matthias Reichl <hias@horus.com>

* systemd: remove provision.conf from tmpfiles.d

provision.conf sets up files from systemd credentials which is
quite useless in LE as we've dropped those.

This fixes the "/root" related error messages from systemd-tmpfiles
in the journal.

Signed-off-by: Matthias Reichl <hias@horus.com>

* openssl: update to 3.5.4

Release notes:
- https://www.openssl.org

Release notes:
- https://www.openssl.org/news/vulnerabilities.html

* filebrowser: update to 2.44.0 and addon (3)

* btrfs-progs: update to 6.17 and addon (3)

* syncthing: update to 2.0.10 and addon (8)

* minisatip: update to 2.0.38 and addon (6)

---------

Signed-off-by: Christian Hewitt <christianshewitt@gmail.com>
Signed-off-by: Matthias Reichl <hias@horus.com>
Signed-off-by: Ian Leonard <antonlacon@gmail.com>
Co-authored-by: Chad Wagner <47257594+wagnerch@users.noreply.github.com>
Co-authored-by: Rudi Heitbaum <rudi@heitbaum.com>
Co-authored-by: Christian Hewitt <christianshewitt@gmail.com>
Co-authored-by: Matthias Reichl <hias@horus.com>
Co-authored-by: CvH <1355173+CvH@users.noreply.github.com>
Co-authored-by: Ian Leonard <antonlacon@gmail.com>
Co-authored-by: Ian Leonard <antonlacon@users.noreply.github.com>
Co-authored-by: Christian Hewitt <chewitt@users.noreply.github.com>